moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_position_controller
    - gripper_controller

  arm_position_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - STS3215_03a-v1_Revolute-45
      - STS3215_03a-v1-1_Revolute-49
      - STS3215_03a-v1-2_Revolute-51
      - STS3215_03a-v1-3_Revolute-53
      - STS3215_03a_Wrist_Roll-v1_Revolute-55

  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: false
    joints:
      - STS3215_03a-v1-4_Revolute-57

