controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    base_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    arm_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


base_velocity_controller:
  ros__parameters:
    joints:
      - ST3215_Servo_Motor-v1-2_Revolute-60
      - ST3215_Servo_Motor-v1-1_Revolute-62
      - ST3215_Servo_Motor-v1_Revolute-64
    interface_name: velocity


arm_position_controller:
  ros__parameters:
    joints:
      - STS3215_03a-v1_Revolute-45
      - STS3215_03a-v1-1_Revolute-49
      - STS3215_03a-v1-2_Revolute-51
      - STS3215_03a-v1-3_Revolute-53
      - STS3215_03a_Wrist_Roll-v1_Revolute-55
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


gripper_controller:
  ros__parameters:
    joints:
      - STS3215_03a-v1-4_Revolute-57
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

