# Default initial positions for LeKiwi's ros2_control fake system

initial_positions:
  STS3215_03a-v1-1_Revolute-49: 0
  STS3215_03a-v1-2_Revolute-51: 0
  STS3215_03a-v1-3_Revolute-53: 0
  STS3215_03a-v1-4_Revolute-57: 0
  STS3215_03a-v1_Revolute-45: 0
  STS3215_03a_Wrist_Roll-v1_Revolute-55: 0