# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm group_controller:
  ros__parameters:
    joints:
      - STS3215_03a-v1_Revolute-45
      - STS3215_03a-v1-1_Revolute-49
      - STS3215_03a-v1-2_Revolute-51
      - STS3215_03a-v1-3_Revolute-53
      - STS3215_03a_Wrist_Roll-v1_Revolute-55
      - STS3215_03a-v1-4_Revolute-57
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true